#!/usr/bin/perl

use	warnings;
use	strict;

die "program x y density mapid" unless (scalar(@ARGV) == 3);

my ($x, $y, $density) = @ARGV;
my $filename = "map";

open(my $fh, '>', $filename); 
print $fh "$y.ox\n";
for (my $i = 0; $i < $y; $i++) {
	for (my $j = 0; $j < $x; $j++) {
		if (int(rand($y) * 2) < $density) {
		   print $fh "o";
		}
		else {
			 print $fh ".";
		}
	}
	print $fh "\n"; 
}

close $fh;
