#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kbethany <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/07 12:57:30 by kbethany          #+#    #+#              #
#    Updated: 2018/10/07 18:02:49 by kbethany         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = eval_expr

SRCS = *.c

all:
	gcc -Wall -Werror -Wextra $(SRCS) -o $(NAME)

clean:
	rm -f *.o

fclean:
	rm -f $(NAME)

re: fclean all